package tools.vitruv.application.demo.familiespersons.persons2families

class PersonsToFamiliesChangePropagationSpecification extends mir.reactions.personsToFamilies.PersonsToFamiliesChangePropagationSpecification {

}