package tools.vitruv.applications.pcmumlcomp.uml2pcm

import mir.reactions.AbstractChangePropagationSpecificationUmlToPcm

class UmlToPcmComponentsChangePropagationSpecification extends AbstractChangePropagationSpecificationUmlToPcm {
	
}