package tools.vitruv.application.demo.familiespersons.families2persons

class FamiliesToPersonsChangePropagationSpecification extends mir.reactions.familiesToPersons.FamiliesToPersonsChangePropagationSpecification {

}