package tools.vitruv.applications.pcmumlclass;

public class CombinedPcmToUmlClassReactionsChangePropagationSpecification
		extends mir.reactions.combinedPcmToUmlClassReactions.CombinedPcmToUmlClassReactionsChangePropagationSpecification {
}
