package tools.vitruv.applications.pcmumlclass;

public class CombinedUmlClassToPcmReactionsChangePropagationSpecification extends
		mir.reactions.combinedUmlClassToPcmReactions.CombinedUmlClassToPcmReactionsChangePropagationSpecification {
}
