package mir.reactions.umlToJava;

import tools.vitruv.extensions.dslsruntime.reactions.AbstractReactionsExecutor;
import tools.vitruv.extensions.dslsruntime.reactions.RoutinesFacadesProvider;

@SuppressWarnings("all")
class ReactionsExecutor extends AbstractReactionsExecutor {
  public ReactionsExecutor() {
    super(new tools.vitruv.domains.uml.UmlDomainProvider().getDomain(), 
    	new tools.vitruv.domains.java.JavaDomainProvider().getDomain());
  }
  
  protected RoutinesFacadesProvider createRoutinesFacadesProvider() {
    return new mir.routines.umlToJava.RoutinesFacadesProvider();
  }
  
  protected void setup() {
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeCreatedInClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeCreatedInDataTypeReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeDeletedFromClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeDeletedFromDataTypeReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeMadeFinalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeTypeChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlLowerMultiplicityChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlUpperMultiplicityChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeRenamedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlAttributeCreatedInInterfaceReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaAttribute.UmlInterfaceMadeFinalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaAttribute"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlClassCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlClassifierRenamedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlClassifierDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlClassMadeFinalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlClassMadeAbstractReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlSuperClassChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlSuperClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlInterfaceImplementerChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlImplementedInterfaceChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlImplementedInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlDataTypeCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlInterfaceCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlSuperInterfaceChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlSuperInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlEnumCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlEnumLiteralCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlEnumLiteralDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlPackageCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlPackageRenamedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlPackageDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaClassifier.UmlPrimitiveTypeCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaClassifier"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlMethodCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlMethodCreatedInDataTypeReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlClassMethodDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlInterfaceMethodDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlDataTypeMethodDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlMethodReturnTypeChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlFeatureMadeStaticReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlMethodMadeAbstractReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlInterfaceMethodCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlMethodMadeFinalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlElementVisibilityChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlNamedElementRenamedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlParameterCreatedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlParameterDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlParameterTypeChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlParameterDirectionChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlParameterDirectionKindChangedInvalidReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlInterfaceMethodVisibilityChangedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
    this.addReaction(new mir.reactions.umlToJavaMethod.UmlInterfaceMethodMadeFinalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath.fromPathString("umlToJava.UmlToJavaMethod"))));
  }
}
