package tools.vitruv.applications.umljava.uml2java

import mir.reactions.reactionsUmlToJava.umlToJava.ChangePropagationSpecificationUmlToJava

class UmlToJavaChangePropagationSpecification extends ChangePropagationSpecificationUmlToJava {
	
}