package tools.vitruv.applications.pcmumlcomponents.uml2pcm

import mir.reactions.reactionsUmlToPcm.umlToPcm.ChangePropagationSpecificationUmlToPcm

class UmlToPcmComponentsChangePropagationSpecification extends ChangePropagationSpecificationUmlToPcm {
	
}