package tools.vitruv.applications.pcmumlcomponents.uml2pcm

import mir.reactions.AbstractChangePropagationSpecificationUmlToPcm

class UmlToPcmComponentsChangePropagationSpecification extends AbstractChangePropagationSpecificationUmlToPcm {
	
}