package tools.vitruv.applications.cbs.equivalencetests

import tools.vitruv.applications.cbs.equivalencetesttemplates.RepositoryEquivalenceTemplate

@ReactionsEquivalenceTest
class RepositoryEquivalenceTest extends RepositoryEquivalenceTemplate {
}
