package tools.vitruv.applications.pcmumlcomp.pcm2uml

import mir.reactions.AbstractChangePropagationSpecification5_1ToUML

class PcmToUmlComponentsChangePropagationSpecification extends AbstractChangePropagationSpecification5_1ToUML {
	
}