package tools.vitruv.applications.pcmumlcomp.pcm2uml

import mir.reactions.AbstractChangePropagationSpecificationPcmToUml

class PcmToUmlComponentsChangePropagationSpecification extends AbstractChangePropagationSpecificationPcmToUml {
	
}