package tools.vitruv.aplications.pcmumlcomp.pcm2uml

import mir.reactions.AbstractChangePropagationSpecificationPcmToUml

class PcmToUmlComponentsChangePropagationSpecification extends AbstractChangePropagationSpecificationPcmToUml {
	
}