package tools.vitruv.applications.demo.insurancefamilies.families2insurance;

class FamiliesToInsuranceChangePropagationSpecification extends mir.reactions.familiesToInsurance.FamiliesToInsuranceChangePropagationSpecification {
	
}
