package tools.vitruv.applications.pcmumlcomponents.pcm2uml

import mir.reactions.reactionsPcmToUml.pcmToUml.ChangePropagationSpecificationPcmToUml

class PcmToUmlComponentsChangePropagationSpecification extends ChangePropagationSpecificationPcmToUml {
	
}