package tools.vitruv.applications.pcmumlcomponents.pcm2uml

import mir.reactions.AbstractChangePropagationSpecificationPcmToUml

class PcmToUmlComponentsChangePropagationSpecification extends AbstractChangePropagationSpecificationPcmToUml {
	
}