package tools.vitruv.applications.demo.insurancefamilies.families2insurance;

public class FamiliesToInsuranceChangePropagationSpecification extends mir.reactions.familiesToInsurance.FamiliesToInsuranceChangePropagationSpecification {
}
