package tools.vitruv.applications.demo.insurancepersons.persons2insurance;

public class PersonsToInsuranceChangePropagationSpecification extends mir.reactions.personsToInsurance.PersonsToInsuranceChangePropagationSpecification {
}
