package tools.vitruv.aplications.umljava.uml2java

import mir.reactions.AbstractChangePropagationSpecificationUmlToJava

class UmlToJavaChangePropagationSpecification extends AbstractChangePropagationSpecificationUmlToJava {
	
}