package tools.vitruv.applications.umljava.java2uml

import mir.reactions.reactionsJavaToUml.javaToUml.ChangePropagationSpecificationJavaToUml

class JavaToUmlChangePropagationSpecification extends ChangePropagationSpecificationJavaToUml {
	
}