package tools.vitruv.applications.joana2c4cbsemodelpreservation.changepropagationspecification;

public class PCM2c4cChangePropagationSpecification extends mir.reactions.pcm2c4c.Pcm2c4cChangePropagationSpecification {}
