package mir.reactions.combinedUmlToPcm;

import tools.vitruv.extensions.dslsruntime.reactions.AbstractReactionsExecutor;
import tools.vitruv.extensions.dslsruntime.reactions.RoutinesFacadesProvider;
import tools.vitruv.extensions.dslsruntime.reactions.structure.ReactionsImportPath;

@SuppressWarnings("all")
class ReactionsExecutor extends AbstractReactionsExecutor {
  public ReactionsExecutor() {
    super(new tools.vitruv.domains.uml.UmlDomainProvider().getDomain(), 
    	new tools.vitruv.domains.pcm.PcmDomainProvider().getDomain());
  }
  
  protected RoutinesFacadesProvider createRoutinesFacadesProvider() {
    return new mir.routines.combinedUmlToPcm.RoutinesFacadesProvider();
  }
  
  protected void setup() {
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentPackageInsertedInPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentPackageRemovedFromPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentPackageDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentClassInsertedInPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentClassRemovedFromPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentOperationInsertedInClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentOperationRemovedFromClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentOperationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentNameReplacedAtOperation_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentNameReplacedAtClass_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmComponent_L2R.OnRepositoryComponentNameReplacedAtPackage_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmComponent_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypePackageInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypePackageDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypeClassInsertedInPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypeClassRemovedFromPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypeClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDataypeNameReplacedAtClass_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDatatypeParentClassInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDatatypeParentClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDatatypeParentGeneralizationInsertedInClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDatatypeParentGeneralizationRemovedFromClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmDatatypes_L2R.OnCompositeDatatypeParentGeneralizationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmDatatypes_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfacePackageInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfacePackageDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceInterfaceInsertedInPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceInterfaceRemovedFromPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceNameReplacedAtInterface_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceParentInterfaceInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceParentInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceParentGeneralizationInsertedInInterfaceReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceParentGeneralizationRemovedFromInterfaceReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmInterface_L2R.OnOperationInterfaceParentGeneralizationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmInterface_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRepository_L2R.OnRepositoryPackageInsertedInPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRepository_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRepository_L2R.OnRepositoryPackageRemovedFromPackageReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRepository_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRepository_L2R.OnRepositoryPackageDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRepository_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRepository_L2R.OnRepositoryNameReplacedAtPackage_nameReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRepository_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRepository_L2R.OnRepositoryNameReplacedAtPackage_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRepository_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleClassInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleInterfaceInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleOperationInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleOperationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRolePropertyInsertedInClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRolePropertyRemovedFromClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRolePropertyDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleInterfaceReplacedAtProperty_typeReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleInterfaceReplacedAtParameter_typeReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleParameterInsertedInOperationReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleParameterRemovedFromOperationReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleParameterDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleNameReplacedAtProperty_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleNameReplacedAtParameter_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnRequiredRoleElementReplacedAtParameter_typeBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleClassInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleClassDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceRealizationInsertedInClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceRealizationRemovedFromClassReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceRealizationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleInterfaceReplacedAtInterfaceRealization_contractReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmRoles_L2R.OnProvidedRoleNameReplacedAtInterfaceRealization_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmRoles_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureInterfaceInsertedAsRootReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureInterfaceDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureOperationInsertedInInterfaceReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureOperationRemovedFromInterfaceReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureOperationDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureParameterInsertedInOperationReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureParameterRemovedFromOperationReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureParameterDeletedReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureNameReplacedAtParameter_nameReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureNameReplacedAtOperation_nameBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlXpcmSignature_L2R.OnSignatureElementReplacedAtParameter_typeBidirectionalReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlXpcmSignature_L2R"))));
    this.addReaction(new mir.reactions.umlReturnAndRegularParameterTypeReactions.RegularOrReturnParameterLowerChanged2Reaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlReturnAndRegularParameterTypeReactions"))));
    this.addReaction(new mir.reactions.umlReturnAndRegularParameterTypeReactions.RegularOrReturnParameterUpperChanged2Reaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm.umlReturnAndRegularParameterTypeReactions"))));
    this.addReaction(new mir.reactions.combinedUmlToPcm.OnParameterDirectionReplacedAtParameterReaction(this.getRoutinesFacadesProvider().getRoutinesFacade(ReactionsImportPath.fromPathString("combinedUmlToPcm"))));
  }
}
